added endpoints for faulty sensor and connection to the mongodb
BondarencoM/KoziBackend pull request #5
Opened 2020-11-10 12:19 UTC by oererenn

2020-11-10 12:24 UTC, MolotovHammr reviewed
Looks great, good job!

2020-11-10 12:32 UTC, michaelbahchevanov requested changes
Could you add tests as well?

2020-11-11 10:24 UTC, BondarencoM commented
@oererenn What's weird is that you depend on mongoose, but don't have it in your list of dependencies in package.json. Obviously for some reason you have it locally.. Do you know what's going on?

2020-11-16 09:59 UTC, larsverp approved these changes, later dismissed

2020-11-16 14:16 UTC, MolotovHammr approved these changes, later dismissed

2020-11-16 14:49 UTC, MolotovHammr submitted a review, later dismissed

2020-11-16 21:51 UTC, BondarencoM requested changes

2020-11-16 21:51 UTC, BondarencoM commented on GraphQL_Express_Server/globalConfig.json
> +{"mongoUri":"mongodb://127.0.0.1:60641/c592808e-5022-4bab-b980-98364e159776?"}
What is the motivation for this file?

2020-11-16 21:51 UTC, BondarencoM commented on GraphQL_Express_Server/graphql/resolvers.js
> +        SensorFaults: () => SensorFault.find({
Do you think we could add a datasaource object and call a method from that object when the resolver is invoked?

2020-11-16 21:51 UTC, BondarencoM commented on GraphQL_Express_Server/models/sensorfault.js
> +        default: Date.now - 1000 * 60 * 60
Why is the default timestamp in the past?

2020-11-16 21:51 UTC, BondarencoM commented on GraphQL_Express_Server/test/mongodbConnection.test.js
> +test('test of reading the entry', async () => {
We need to also test that the time range works as intended.

2020-11-17 13:06 UTC, BondarencoM approved these changes

2020-11-17 15:52 UTC, michaelbahchevanov approved these changes
Looks great!

2020-11-18 13:36 UTC, MolotovHammr approved these changes

2020-11-20 12:36 UTC, larsverp approved these changes
rip package-lock

2020-11-21 14:09 UTC, merged